export const metadata = {
    title: 'Nazmul',
    description: 'Generated by create next app',
}

const Nazmul = () => {



    return (
        <div>
            <p>Nazmul`s Pages</p>
        </div>
    );
};

export default Nazmul;